"""Public surface for the db subpackage. Mirrors the old `token_dashboard.db` module."""
from .schema import (
    SCHEMA,
    connect,
    default_db_path,
    init_db,
)
from .projects import (
    best_project_name,
    project_name_for,
)
from .queries import (
    add_session_tag,
    all_tags,
    current_session_anchor,
    daily_token_breakdown,
    expensive_prompts,
    hourly_breakdown,
    model_breakdown,
    overview_totals,
    phase_split,
    project_summary,
    recent_sessions,
    remove_session_tag,
    session_ids_with_tag,
    session_tags,
    session_turns,
    skill_breakdown,
    tool_token_breakdown,
    window_billable_tokens,
    EXECUTE_TOOLS,
    PLAN_TOOLS,
    SESSION_HOURS,
)

__all__ = [
    "SCHEMA",
    "EXECUTE_TOOLS",
    "PLAN_TOOLS",
    "SESSION_HOURS",
    "add_session_tag",
    "all_tags",
    "best_project_name",
    "connect",
    "current_session_anchor",
    "daily_token_breakdown",
    "default_db_path",
    "expensive_prompts",
    "hourly_breakdown",
    "init_db",
    "model_breakdown",
    "overview_totals",
    "phase_split",
    "project_name_for",
    "project_summary",
    "recent_sessions",
    "remove_session_tag",
    "session_ids_with_tag",
    "session_tags",
    "session_turns",
    "skill_breakdown",
    "tool_token_breakdown",
    "window_billable_tokens",
]
